version: '3'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    expose:
      - "8080"
    volumes:
      - project:/home/gcamargo/Todo-List-with-User-Authentication/
    ports:
      - "8000:8080"

volumes:
  project: